### ISSUE TITLE
Does not build with latest sbcl - use of SB-FORMAT::*FORMAT-WHITESPACE-CHARS*

### ISSUE THREAD

**Issue by quicklisp** [ha-mo-we/Racer#16]
https://github.com/ha-mo-we/Racer/blob/master/source/tools.lisp#L482 is the problem. It's not present in the latest SBCL. Build log is here: http://report.quicklisp.org/2018-10-18/failure-report/racer.html#racer

**Comment by quicklisp** [comment]
If this is not fixed, I won't be able to include racer in the next Quicklisp update.

**Comment by ha-mo-we** [comment]
Sorry for not having reacted promptly. I was waiting for 1.4.10 to be available for MacOS. 
According to the SBCL download page, 1.4.14 is available for AMD64/Linux only.
I will check out what I can do. 

Regards,
Ralf

**Comment by quicklisp** [comment]
You have to build your own. It is easy though.

**Comment by binghe** [comment]
Besides, if you install SBCL from Homebrew [1], you will (almost) always have the current latest SBCL at `/usr/local/bin/sbcl`. This installation works perfectly for everyone who doesn't need to customize SBCL with special build options.

[1] https://brew.sh

**Comment by PuercoPop** [comment]
FWIW the issue can be easily fixed if we limit ourselves to SBCL versions built with unicode support by replacing the failing form with `(sb-unicode:whitespace-p char)`

```patch
@@ -479,7 +479,7 @@ (defun whitespace-char-p (char)
   #+(and :allegro (or :allegro-v9.0 :allegro-v10.0))
   (excl::whitespace-char-p char)
   #+:sbcl
-  (find char SB-FORMAT::*FORMAT-WHITESPACE-CHARS*)
+  (sb-unicode:whitespace-p char)
   #+:ccl (ccl:whitespacep char)
   #+(and (not :allegro) (not :lispworks) (not :sbcl) (not :ccl))
   (to-be-implemented 'whitespace-char-p))
```

**Comment by quicklisp** [comment]
Another option is to just use the three characters directly, #\Space,
#\Newline, #\Tab.

**Comment by ha-mo-we** [comment]
> On 30. Nov 2018, at 14:33, Zach Beane <notifications@github.com> wrote:
> 
> Another option is to just use the three characters directly, #\Space,
> #\Newline, #\Tab.

I replaced SB-FORMAT::*FORMAT-WHITESPACE-CHARS* with #(#\  #\Newline #\Tab) for the time being and updated Racer on Github.

Thank you for pointing out the problem. Hopefully now Racer compiles.

Best regards,
Ralf

**Comment by ha-mo-we** [comment]
Seems sbcl 1.4.13 still causes problems. Stay tuned...

**Comment by ha-mo-we** [comment]
> On 30. Nov 2018, at 12:51, Chun Tian <notifications@github.com> wrote:
> 
> Besides, if you install SBCL from Homebrew [1], you will (almost) always have the current latest SBCL at /usr/local/bin/sbcl. This installation works perfectly for everyone who doesn't need to customize SBCL with special build options.

Thanks for pointing this out. I successfully installed SBCL 1.4.13 using Homebrew.

--Ralf

**Comment by ha-mo-we** [comment]
Somehow, at least with my system, the package "ironclad" does not compile under 1.4.13.

**Comment by quicklisp** [comment]
Make sure to use the latest Quicklisp dist via (ql:update-dist "quicklisp")
- there were some breaking changes that were fixed.

**Comment by ha-mo-we** [comment]
> On 30. Nov 2018, at 14:28, Javier Olaechea <notifications@github.com> wrote:
> 
> FWIW the issue can be easily fixed if we limit ourselves to SBCL versions built with unicode support by replacing the failing form with (sb-unicode:whitespace-p char)
> 
> @@ -479,7 +479,7 @@
>  (defun whitespace-char-p (char)
>    #+(and :allegro (or :allegro-v9.0 :allegro-v10.0))
>    (excl::whitespace-char-p char)
>    #+:sbcl
> 
> -  (find char SB-FORMAT::*FORMAT-WHITESPACE-CHARS*)
> +  (sb-unicode:whitespace-p char)

Yes, thank you, this probably works. I am, however, struggling with other packages (e.g., ironclad) in SBCL 1.4.13.

**Comment by ha-mo-we** [comment]
> On 2. Dec 2018, at 14:21, Zach Beane <notifications@github.com> wrote:
> 
> Make sure to use the latest Quicklisp dist via (ql:update-dist "quicklisp")
> - there were some breaking changes that were fixed.
> 
> 

I installed Quicklisp again and started from scratch. 

Unfortunately, it seems that required packages are not correctly found that are specified in a (:require "module") clause in the :depends-on spec inside asdf:defsystem

(asdf:defsystem "racer"
  :description "Description Logic Reasoner"
  :author "Volker Haarslev, Ralf Moeller, Michael Wessel"
  :mailto "haarslev@cs.concordia.ca, moeller@uni-luebeck.de, miacwess@gmail.com"
  :license "BSD 3"
  :homepage "http://www.racer-systems.com"
  :pathname #P"racer:source;"
  :serial t
  :depends-on (#-:abcl (:require "aserve") 
               #-:allegro (:require "flexi-streams")
               #-:allegro (:require "deflate")


I first had to do a (ql:quickload "aserve"), (ql:quickload "flexi-streams"), (ql:quickload "deflate") before compiling Racer.

Here is the error message if the latter two are not loaded manually.

* (ql:quickload "racer")
To load "racer":
  Load 1 ASDF system:
    racer
; Loading "racer"

debugger invoked on a SB-INT:EXTENSION-FAILURE in thread
#<THREAD "main thread" RUNNING {10005185B3}>:
  Don't know how to REQUIRE flexi-streams.
See also:
  The SBCL Manual, Variable *MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     completing load for #<REQUIRE-SYSTEM "flexi-streams">.
  1: [ACCEPT                       ] Continue, treating
                                     completing load for #<REQUIRE-SYSTEM "flexi-streams">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "racer"
  7:                                 Exit debugger, returning to top level.

(REQUIRE "flexi-streams" NIL)
0] 

Then, Quicklisp is puzzled:

(ql:quickload "flexi-streams")
To load "flexi-streams":
  Load 1 ASDF system:
    flexi-streams
; Loading "flexi-streams"

debugger invoked on a SB-INT:EXTENSION-FAILURE in thread
#<THREAD "main thread" RUNNING {10005185B3}>:
  Don't know how to REQUIRE flexi-streams.
See also:
  The SBCL Manual, Variable *MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     completing load for #<REQUIRE-SYSTEM "flexi-streams">.
  1: [ACCEPT                       ] Continue, treating
                                     completing load for #<REQUIRE-SYSTEM "flexi-streams">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "flexi-streams"
  7:                                 Exit debugger, returning to top level.

(REQUIRE "flexi-streams" NIL)
0] 


Strangely, after restarting SBCL, (ql:quickload "flexi-streams") works fine again.

Quickloading "aserve" compiles and loads "ironclad", so this error is gone.
After having executed (ql:quickload "aserve"), (ql:quickload "flexi-streams"), (ql:quickload "deflate") manually, 
I was able to compile Racer w/o problems with SB-FORMAT::*FORMAT-WHITESPACE-CHARS* being
replaced as mentioned in my previous email.

Does the :require statement in asdf (3.3.1) no longer work (in SBCL)?

Best regards,
Ralf

**Comment by quicklisp** [comment]
I don't know, but racer builds fine for me. lracer has the same sb-format problem though.

**Comment by ha-mo-we** [comment]
> On 4. Dec 2018, at 15:11, Zach Beane <notifications@github.com> wrote:
> 
> I don't know, but racer builds fine for me.
> 
I installed Quicklisp from scratch, and I tried to compile Racer (my local files) -- with problems as reported. In the defsystem form, the racer asd file uses :require for aserve, flexi-streams and deflate. Once I ql:quickloaded these systems manually (and therefore local systems are available on my computer) everything works fine for me as well. Apparently, there is a problem when Quicklisp needs to first download respective modules while loading another system is loaded that uses modules. I will check this out in more detail. Stay tuned.
> lracer has the same sb-format problem though.
> 
> 

Yes, I am sorry -- fixed. Github is already updated.

Please note that lracer is not compatible with racer due to unavoidable symbol clashes. 
lracer is to be loaded in a fresh lisp to access racer remotely.

-Ralf

**Comment by ha-mo-we** [comment]
I also fixed the incompatibility between lracer and racer in the latest Github contrib.

**Comment by quicklisp** [comment]
I don't see the lracer fix in github yet. I still see the problem at https://github.com/ha-mo-we/Racer/blob/master/clients/lracer/lracer-reader-macros.lisp#L65

**Comment by ha-mo-we** [comment]
Oh oh. I am using another Mac while my old one gets repaired (need a new battery after 6 years). 
It is completely unclear to me why Github Desktop indicates successful updates locally to me, while, yes, 
they are not visible globally. Sorry for the problems. Hopefully, tomorrow the old Mac is in operation 
again and I can check in the lracer update.

**Comment by ha-mo-we** [comment]
Seems I was able to upload the respective files.

**Comment by gschadow** [comment]
SBCL 1.4.14 here on Windows and built without a problem using quick-lisp. Like magic.
